### ISSUE TITLE
Feature Request: A config option to increase the number of songs shown when using the queue command

### ISSUE THREAD

**Issue by 2KDrop** [museofficial/muse#1039]
I was wondering if this might be possible, as it can be a bit of a pain to view what is queued without filling the chat with many queue commands

**Comment by codetheweb** [comment]
happy to accept a PR for this!

**Comment by codetheweb** [comment]
🚀 Released in [Release v2.9.4](https://github.com/museofficial/muse/releases/tag/v2.9.4).
