### ISSUE TITLE
🔎 looking for maintainers

### ISSUE THREAD

**Issue by codetheweb** [museofficial/muse#1063]
I haven't used Muse myself in over 3 years and I've been struggling to spend enough time on it lately to meet my personal quality standard for an active open source project. I would love to onboard someone who actually uses Muse to take over the project and help ensure a healthy, happy community.

I'm looking for someone who:

- is passionate about creating software that doesn't suck
- knows TypeScript or is happy to learn
- (ideally) has some level of experience maintaining larger open source projects

I would be happy to move this repo to a new organization or archive it and point to a fork to signal that I'm no longer the primary maintainer and that someone else deserves the credit.

Reply here if you're interested!

**Comment by Hazzajenko** [comment]
Hey, I'm interested in becoming a Muse maintainer! My friends and I use Muse on our server, and I'd love to keep it going.

**Comment by TaylorTWBrown** [comment]
Hi, I'm happy to help as a maintainer. I'm versed in git and node, and run it with friends who are also programmers.

**Comment by shiftybitshiftr** [comment]
Hi there, my Discord has used and loved Muse for years. I would love to contribute and be a maintainer. 

I've made local patches to muse at my friends' request, and prior I made minor PRs to JustSomeBots/MusicBot. 
I'm currently an InfoSec engineer at a Fortune 500, and while I'm not versed in TypeScript, I'm happy to learn and enjoy tinkering in my free time. 

Regardless, I'm surprised to hear you haven't used it in 3 years yet continued to maintain it - thanks for your dedication!

**Comment by JoeWHoward** [comment]
I don't know that I have the capacity to be "the maintainer", but I am happy to help out with development if any maintainer steps up to coordinate tickets/issues.  Have been running Muse for at least a year, and fit 2/3 criteria ;)

**Comment by codetheweb** [comment]
I really appreciate all the interest! Based on the number of responses I'll transfer Muse to an org this weekend and give people permission on the org. Thank you!

**Comment by shiftybitshiftr** [comment]
Hey there, happy to contribute as well. Thanks for maintaining the bot for all these years, despite not even using it! :)

**Comment by codetheweb** [comment]
Updates:

- I've transferred Muse to a new org. Happy to change the name if anyone has a better suggestion, all the good ones seemed to be taken. 
- I invited everyone in this thread to the org.
- Still working on setting up CD.
- Images will be published to ghcr.io/museofficial/muse (as well as codetheweb/muse for the time being). DockerHub doesn't have free orgs.

I'm happy to meet with people if you have any questions, my email is on https://maxisom.me.

**Comment by codetheweb** [comment]
- CD is fixed.
- I added docs for how to release new versions: https://github.com/museofficial/muse/blob/master/RELEASING.md.

The ship is yours. :) Looks like there's a PR for bumping the ytdl-core version if anyone wants to try merging & releasing it as a trial run.

**Comment by Codixer** [comment]
@codetheweb 
It seems a lil... inactive. Still taiking additional maintainers that want to contribute?
![image](https://github.com/user-attachments/assets/af2cecab-f516-4515-801f-df44761c3533)

**Comment by codetheweb** [comment]
sure, want me to add you?

**Comment by Codixer** [comment]
> sure, want me to add you?
If possible, sure yeah.

**Comment by codetheweb** [comment]
invited

**Comment by soulwax** [comment]
I'm working on it alone since forever and would like to participate. See https://github.com/soulwax/ECHO
