### ISSUE TITLE
Bot plays music video when using spotify link

### ISSUE THREAD

**Issue by someone12421** [museofficial/muse#1093]
**What's happening?**
Concisely describe what's going wrong.

when i use a spotify link, the bot plays the youtube video for the music video instead of the one thats just the song.
is there any way to change this?

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [x] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.9.4
- Docker (if applicable): 27.2.0
- OS: Ubuntu server 24.04 LTS

**Comment by JoeWHoward** [comment]
Muse currently does not have the capability to distinguish songs vs music videos.

Muse cannot play songs directly from Spotify's API, so instead it [fetches the song name and artist name from Spotify's API](https://github.com/museofficial/muse/blob/534d8fafaa7f09f7ba940d044b08e6c48f800c7a/src/services/get-songs.ts#L45-L48), then [searches YouTube for `"Track Name" "Artist Name"` ](https://github.com/museofficial/muse/blob/534d8fafaa7f09f7ba940d044b08e6c48f800c7a/src/services/get-songs.ts#L83-L85).  It picks the top result, which in this case, is likely a music video.

You could try enabling SponsorBlock, which might skip through intro scenes of a music video (if that is why you want to avoid music videos) by setting the environment variable `ENABLE_SPONSORBLOCK=true` or uncomment it in your .env

Alternatively, you can create a YouTube Playlist and play that with Muse, or queue up the specific YouTube URL that you want to hear.

**Comment by JoeWHoward** [comment]
If you are running Muse with Docker Compose, you can add 

```
- ENABLE_SPONSORBLOCK=true
```

Underneath your existing environment variables (with the same indentation).  Else, you can add `-e ENABLE_SPONSORBLOCK='true'` to your Docker `docker run`command.
