### ISSUE TITLE
After some time the bot just randomly starts to work

### ISSUE THREAD

**Issue by Mr3DAlien** [museofficial/muse#1115]
**What's happening?**
Basically I use the Bot and everything works fine, it then however stops working after weeks of running fine and there is no way to repair it. I had this once and I honestly don't know how I fixed it exactly, because what I did was redo everything. So make new Accounts, new Youtube API Keys and so on. Now I am at the stage again where I can request a song, the bot will join and say Now Playing: My Song, but doesn't do anything. I use the correct repository as mentioned in your text and I also should be on the latest version

**Logs**

```

```

**Screenshots**

**Additional context**

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [X ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.9.4
- Docker (Portainer 2.21.4):
- OS: Linux Debian 12
- Node.js: (if running outside the Docker container)
- ffmpeg: (if running outside the Docker container, 4.1 or later is required)

**Comment by Codixer** [comment]
Possibly, this could have been Youtube removing your API key. This sometimes happens when a key is abused.
