### ISSUE TITLE
Unable to play YouTube URL's 

### ISSUE THREAD

**Issue by kezzkezzkezz** [museofficial/muse#1134]
**What's happening?**
Can query a song and play either youtube or spotify but cant paste a URL 

**Logs**

```

```

**Screenshots**
![image](https://github.com/user-attachments/assets/179827da-0b2f-4b90-a61f-2927c4663ea9)
![image](https://github.com/user-attachments/assets/8e798a89-af49-4d7e-94d0-1726b53bdd16)

**Additional context**

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [*] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse:2.9.5
- Docker (if applicable):
- OS: UNRAID
- Node.js: (if running outside the Docker container)
- ffmpeg: (if running outside the Docker container, 4.1 or later is required)

**Comment by Codixer** [comment]
This might be an issue with your client rather then the bot, as we do not control the validation on discord's side for slash commands
