### ISSUE TITLE
[bug]: When config set-reduce-vol-when-voice is set to True, set max volume is not respected

### ISSUE THREAD

**Issue by sypion** [museofficial/muse#1143]
**What's happening?**
When `/config set-reduce-vol-when-voice` is used and set to `True`, if someone were to speak, the bot functions correctly by temporarily lowering the volume to an amount specified, however, the volume returns to 100% instead of the currently set volume, for example, 20%, when everyone in the voice channel is no longer speaking.

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [X] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.10.0
- Docker (if applicable): 27.3.1
- OS: Debian GNU/Linux 12 (bookworm)

**Comment by Codixer** [comment]
Mind trying with `ghcr.io/museofficial/muse:pr-1146`?
