### ISSUE TITLE
Feature Request: Have Muse Stay in Channel

### ISSUE THREAD

**Issue by Zereah** [museofficial/muse#1176]
Hi there, loving Muse so far. Would be nice if there was functionality to have it remain in the voice channel even when the queue is currently empty.

Thanks!

**Comment by Br0mmie** [comment]
Hey Zereah!

There is a command for this
`/config set-wait-after-queue-empties 0`

This will basically just set it so it never leaves!

Hope it helps!

**Comment by RyanStav1994** [comment]
unfortunately on the current release setting this command with value 0 does not work even after restarting the bot completely. It did work in the past  @Br0mmie

**Comment by Br0mmie** [comment]
I did it today and it worked perfectly

**Comment by RyanStav1994** [comment]
<img width="483" alt="Discord_7Ih5CiPCJU" src="https://github.com/user-attachments/assets/97e0893c-dce5-487c-8379-a0813d3b9067" />
It is set, but will leave after the queue is empty after about a minute

**Comment by Br0mmie** [comment]
Sorry mate but that is not whats happening on my end

**Comment by Br0mmie** [comment]
![proof](https://github.com/user-attachments/assets/3d9ce121-36e4-4ec6-8a63-46af4c938739)
And here is the proof

**Comment by Zereah** [comment]
> Hey Zereah!
> 
> There is a command for this `/config set-wait-after-queue-empties 0`
> 
> This will basically just set it so it never leaves!
> 
> Hope it helps!

Thanks for the tip! Had no idea that was available in the config (or that there were additional config options to begin with... oops.)
