### ISSUE TITLE
unable to add users to role after integration

### ISSUE THREAD

**Issue by DVDIsDead** [museofficial/muse#560]
I followed the new instructions to set up the bot to a role, however, I'm unable to manage users in that role afterwards, rendering the role aspect useless. discord says it has to be managed by the bot, and the role disappears from the role list in right-click. 

is there something I'm missing? I've temporarily told the server owner to run the config command with no role specified, which changes the role to "@@everyone" and then we can all use it, but the role previously set is still "integrated" with the bot and rendered unmanageable

**Comment by codetheweb** [comment]
Sorry, I'm not entirely sure what you're asking. When you invite a bot to a Discord server, it creates an autogenerated read-only role for the bot to use--but this role is not supposed to be assigned to actual members.

The idea with the role system in Muse is that you would create a new role, say `@dj`, give it to members who should be able to use Muse, then `/config set-role @dj`.
