### ISSUE TITLE
Bot is stuck on "Sending Command..." in Discord

### ISSUE THREAD

**Issue by giomxx** [museofficial/muse#617]
**What's happening?**
Concisely describe what's going wrong.

When trying to run a command in discord, it is just stuck on "sending command...". I have tried multiple commands, on multiple servers, and multiple installations of the bot. 

No logs, or console output is created past the "Ready!" message.

**Logs**

```

```

**Screenshots**

![image](https://user-images.githubusercontent.com/34938366/161873119-1813a04d-9e8b-4c97-b5b2-56d2e76353f3.png)

**Additional context**

**Runtime**
I'm running Muse:
- [x] Directly from the cloned repository
- [ ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: latest
- Docker (if applicable):
- OS: Windows 10 Home

**Comment by hubret** [comment]
I'm assuming youre using the latest version of muse?

I'm also seeing this when trying to set role after a fresh upgrade (1.6 -> 1.8.2): 
![image](https://user-images.githubusercontent.com/8590448/161995076-34114987-5ec0-4168-8a81-50ac8f2ac955.png)

Nothing in console either.

**Comment by giomxx** [comment]
Yeah it is a weird one, I'm on a fresh install of the latest. Mine doesn't even get to "Application did not respond", it just infinitely loads

**Comment by codetheweb** [comment]
Have you both run `yarn install`? A dependency was recently changed that might be causing this.

**Comment by hubret** [comment]
I've run `npm i` after checking out each tag I tested. That's good to know, I might try to boot this up from scratch if it might be an old package left over for some reason.

**Comment by giomxx** [comment]
I've been using `npm i` instead of yarn, a completely fresh install, following the install guide on the readme

**Comment by codetheweb** [comment]
@giomxx can you run in debug mode by setting the environment variable `DEBUG` to `*` and post the output? (`DEBUG=* npm run start` on *sh)

**Comment by codetheweb** [comment]
@joepboumans I'm pretty sure your issue is unrelated and outside the scope of Muse; it looks like your DNS server might be flakey.
